import { apiClient } from './client';
import type { ApiResult } from './client';
import type { Expense, ExpensesResponse } from '../types/expense';

export interface CreateExpensePayload {
  amount: string; // string — always string input, never raw JS float
  category: string;
  description: string;
  date: string; // "YYYY-MM-DD"
  idempotency_key: string; // UUID v4 generated by client on mount
}

export function getExpenses(params: {
  category?: string;
}): Promise<ApiResult<ExpensesResponse>> {
  const queryString = params.category
    ? `?category=${encodeURIComponent(params.category)}`
    : '';
  return apiClient.get<ExpensesResponse>(`/expenses${queryString}`);
}

export function createExpense(
  payload: CreateExpensePayload
): Promise<ApiResult<Expense>> {
  return apiClient.post<Expense>('/expenses', payload);
}
